ANALYSIS_PASSES = ['stack-safety', 'cfl-anders-aa', 'fam-proxy', 'no-op-cgscc', 'assumptions', 'func-properties',
                   'divergence', 'targetlibinfo', 'globals-aa', 'scalar-evolution', 'inline-advisor', 'no-op-loop',
                   'pass-instrumentation', 'cfl-steens-aa', 'lcg', 'no-op-module', 'ddg', 'access-info', 'regions',
                   'memoryssa', 'module-summary', 'scoped-noalias-aa', 'demanded-bits', 'callgraph', 'branch-prob',
                   'stack-safety-local', 'domtree', 'lazy-value-info', 'iv-users', 'postdomtree', 'basic-aa', 'loops',
                   'ir-similarity', 'aa', 'da', 'block-freq', 'objc-arc-aa', 'no-op-function', 'tbaa', 'verify',
                   'phi-values', 'opt-remark-emit', 'scev-aa', 'targetir', 'memdep', 'inliner-size-estimator',
                   'profile-summary', 'domfrontier']

TRANSFORM_PASSES = ['globalopt', 'scalarizer', 'load-store-vectorizer', 'rewrite-statepoints-for-gc',
                    'separate-const-offset-from-gep', 'unify-loop-exits', 'objc-arc', 'name-anon-globals',
                    'lower-guard-intrinsic', 'objc-arc-contract', 'lower-matrix-intrinsics', 'loop-rotate',
                    'memprof-module', 'strip-nonlinetable-debuginfo', 'synthetic-counts-propagation', 'lowertypetests',
                    'strip-gc-relocates', 'forceattrs', 'reassociate', 'infer-address-spaces', 'libcalls-shrinkwrap',
                    'div-rem-pairs', 'simple-loop-unswitch', 'inliner-wrapper-no-mandatory-first', 'gvn-sink',
                    'early-cse-memssa', 'add-discriminators', 'sroa', 'function-import', 'memcpyopt', 'guard-widening',
                    'helloworld', 'jump-threading', 'strip', 'coro-cleanup', 'break-crit-edges', 'canonicalize-aliases',
                    'reg2mem', 'openmp-opt-cgscc', 'instrprof', 'pseudo-probe', 'loop-distribute', 'sink', 'adce',
                    'loop-simplifycfg', 'loop-extract-single', 'function-attrs', 'post-inline-ee-instrument',
                    'view-cfg', 'indvars', 'rel-lookup-table-converter', 'float2int', 'loop-versioning-licm',
                    'called-value-propagation', 'fix-irreducible', 'loop-unroll', 'cg-profile', 'partial-inliner',
                    'pgo-memop-opt', 'inliner-wrapper', 'no-op-module', 'correlated-propagation', 'memprof', 'lcssa',
                    'lower-widenable-condition', 'assume-builder', 'always-inline', 'wholeprogramdevirt',
                    'tailcallelim', 'function-specialization', 'loop-bound-split', 'sccp', 'dot-cfg', 'mergefunc',
                    'iroutliner', 'loop-reduce', 'aggressive-instcombine', 'globalsplit', 'attributor', 'instcombine',
                    'lowerswitch', 'pgo-instr-gen', 'mergereturn', 'loop-reroll', 'loop-load-elim', 'pgo-instr-use',
                    'lnicm', 'no-op-function', 'verify', 'instsimplify', 'strip-dead-prototypes', 'argpromotion',
                    'vector-combine', 'ee-instrument', 'structurizecfg', 'scc-oz-module-inliner', 'objc-arc-apelim',
                    'loop-extract', 'scalarize-masked-mem-intrin', 'loop-idiom', 'pseudo-probe-update',
                    'strip-dead-debug-info', 'nary-reassociate', 'sample-profile', 'loop-vectorize', 'no-op-cgscc',
                    'insert-gcov-profiling', 'constmerge', 'loop-data-prefetch', 'hotcoldsplit', 'slsr', 'internalize',
                    'mem2reg', 'instrorderfile', 'loop-unroll-full', 'pgo-icall-prom', 'rpo-function-attrs',
                    'annotation-remarks', 'globaldce', 'simplifycfg', 'loweratomic', 'speculative-execution',
                    'strip-nondebug', 'attributor-cgscc', 'lower-constant-intrinsics', 'chr', 'coro-early',
                    'make-guards-explicit', 'gvn', 'inferattrs', 'bdce', 'loop-deletion', 'licm', 'elim-avail-extern',
                    'loop-versioning', 'early-cse', 'loop-predication', 'gvn-hoist', 'cross-dso-cfi',
                    'inject-tli-mappings', 'invalidate', 'metarenamer', 'lowerinvoke', 'loop-instsimplify',
                    'coro-elide', 'poison-checking', 'dot-ddg', 'rewrite-symbols', 'extract-blocks',
                    'annotation2metadata', 'lower-expect', 'loop-interchange', 'strip-debug-declare', 'view-cfg-only',
                    'inline', 'dot-cfg-only', 'irce', 'instnamer', 'deadargelim', 'objc-arc-expand', 'no-op-loop',
                    'loop-unroll-and-jam', 'dce', 'alignment-from-assumptions', 'loop-simplify', 'ipsccp',
                    'slp-vectorizer', 'loop-fusion', 'loop-sink', 'consthoist', 'partially-inline-libcalls',
                    'mldst-motion', 'aa-eval', 'redundant-dbg-inst-elim', 'loop-flatten', 'callsite-splitting',
                    'newgvn', 'dse', 'assume-simplify', 'lint', 'constraint-elimination', 'coro-split', 'openmp-opt',
                    'transform-warning', 'canon-freeze', 'lower-matrix-intrinsics-minimal', 'mergeicmps',
                    'dfa-jump-threading', 'instcount', 'bounds-checking']

PRINTER_PASSES = ['print-stack-safety', 'print-predicateinfo', 'print-lcg', 'print', 'print-ir-similarity',
                  'print-profile-summary', 'print-memderefs', 'print-callgraph', 'print-must-be-executed-contexts',
                  'print-alias-sets', 'print-mustexecute', 'print-access-info', 'print-lcg-dot']

SANITIZER_PASSES = ['sancov-module', 'hwasan', 'tsan-module', 'msan-module', 'khwasan', 'asan', 'msan', 'kasan',
                    'asan-globals-md', 'dfsan', 'kasan-module', 'kmsan', 'asan-module', 'tsan']

ALL_PASSES = ['stack-safety', 'cfl-anders-aa', 'fam-proxy', 'no-op-cgscc', 'assumptions', 'func-properties',
              'divergence', 'targetlibinfo', 'globals-aa', 'scalar-evolution', 'inline-advisor', 'no-op-loop',
              'pass-instrumentation', 'cfl-steens-aa', 'lcg', 'no-op-module', 'ddg', 'access-info', 'regions',
              'memoryssa', 'module-summary', 'scoped-noalias-aa', 'demanded-bits', 'callgraph', 'branch-prob',
              'stack-safety-local', 'domtree', 'lazy-value-info', 'iv-users', 'postdomtree', 'basic-aa', 'loops',
              'ir-similarity', 'aa', 'da', 'block-freq', 'objc-arc-aa', 'no-op-function', 'tbaa', 'verify',
              'phi-values', 'opt-remark-emit', 'scev-aa', 'targetir', 'memdep', 'inliner-size-estimator',
              'profile-summary', 'domfrontier', 'globalopt', 'scalarizer', 'load-store-vectorizer',
              'rewrite-statepoints-for-gc', 'separate-const-offset-from-gep', 'unify-loop-exits', 'objc-arc',
              'name-anon-globals', 'lower-guard-intrinsic', 'objc-arc-contract', 'lower-matrix-intrinsics',
              'loop-rotate', 'memprof-module', 'strip-nonlinetable-debuginfo', 'synthetic-counts-propagation',
              'lowertypetests', 'strip-gc-relocates', 'forceattrs', 'reassociate', 'infer-address-spaces',
              'libcalls-shrinkwrap', 'div-rem-pairs', 'simple-loop-unswitch', 'inliner-wrapper-no-mandatory-first',
              'gvn-sink', 'early-cse-memssa', 'add-discriminators', 'sroa', 'function-import', 'memcpyopt',
              'guard-widening', 'helloworld', 'jump-threading', 'strip', 'coro-cleanup', 'break-crit-edges',
              'canonicalize-aliases', 'reg2mem', 'openmp-opt-cgscc', 'instrprof', 'pseudo-probe', 'loop-distribute',
              'sink', 'adce', 'loop-simplifycfg', 'loop-extract-single', 'function-attrs', 'post-inline-ee-instrument',
              'view-cfg', 'indvars', 'rel-lookup-table-converter', 'float2int', 'loop-versioning-licm',
              'called-value-propagation', 'fix-irreducible', 'loop-unroll', 'cg-profile', 'partial-inliner',
              'pgo-memop-opt', 'inliner-wrapper', 'no-op-module', 'correlated-propagation', 'memprof', 'lcssa',
              'lower-widenable-condition', 'assume-builder', 'always-inline', 'wholeprogramdevirt', 'tailcallelim',
              'function-specialization', 'loop-bound-split', 'sccp', 'dot-cfg', 'mergefunc', 'iroutliner',
              'loop-reduce', 'aggressive-instcombine', 'globalsplit', 'attributor', 'instcombine', 'lowerswitch',
              'pgo-instr-gen', 'mergereturn', 'loop-reroll', 'loop-load-elim', 'pgo-instr-use', 'lnicm',
              'no-op-function', 'verify', 'instsimplify', 'strip-dead-prototypes', 'argpromotion', 'vector-combine',
              'ee-instrument', 'structurizecfg', 'scc-oz-module-inliner', 'objc-arc-apelim', 'loop-extract',
              'scalarize-masked-mem-intrin', 'loop-idiom', 'pseudo-probe-update', 'strip-dead-debug-info',
              'nary-reassociate', 'sample-profile', 'loop-vectorize', 'no-op-cgscc', 'insert-gcov-profiling',
              'constmerge', 'loop-data-prefetch', 'hotcoldsplit', 'slsr', 'internalize', 'mem2reg', 'instrorderfile',
              'loop-unroll-full', 'pgo-icall-prom', 'rpo-function-attrs', 'annotation-remarks', 'globaldce',
              'simplifycfg', 'loweratomic', 'speculative-execution', 'strip-nondebug', 'attributor-cgscc',
              'lower-constant-intrinsics', 'chr', 'coro-early', 'make-guards-explicit', 'gvn', 'inferattrs', 'bdce',
              'loop-deletion', 'licm', 'elim-avail-extern', 'loop-versioning', 'early-cse', 'loop-predication',
              'gvn-hoist', 'cross-dso-cfi', 'inject-tli-mappings', 'invalidate', 'metarenamer', 'lowerinvoke',
              'loop-instsimplify', 'coro-elide', 'poison-checking', 'dot-ddg', 'rewrite-symbols', 'extract-blocks',
              'annotation2metadata', 'lower-expect', 'loop-interchange', 'strip-debug-declare', 'view-cfg-only',
              'inline', 'dot-cfg-only', 'irce', 'instnamer', 'deadargelim', 'objc-arc-expand', 'no-op-loop',
              'loop-unroll-and-jam', 'dce', 'alignment-from-assumptions', 'loop-simplify', 'ipsccp', 'slp-vectorizer',
              'loop-fusion', 'loop-sink', 'consthoist', 'partially-inline-libcalls', 'mldst-motion', 'aa-eval',
              'redundant-dbg-inst-elim', 'loop-flatten', 'callsite-splitting', 'newgvn', 'dse', 'assume-simplify',
              'lint', 'constraint-elimination', 'coro-split', 'openmp-opt', 'transform-warning', 'canon-freeze',
              'lower-matrix-intrinsics-minimal', 'mergeicmps', 'dfa-jump-threading', 'instcount', 'bounds-checking']
