FAILED_PASSES = ['fam-proxy', 'no-op-cgscc', 'assumptions', 'func-properties', 'inline-advisor', 'no-op-loop',
                 'pass-instrumentation', 'lcg', 'no-op-module', 'ddg', 'access-info', 'callgraph', 'ir-similarity',
                 'no-op-function', 'opt-remark-emit', 'targetir', 'inliner-size-estimator', 'profile-summary',
                 'synthetic-counts-propagation', 'inliner-wrapper-no-mandatory-first', 'function-import', 'helloworld',
                 'pseudo-probe', 'rel-lookup-table-converter', 'inliner-wrapper', 'no-op-module', 'loop-bound-split',
                 'pgo-instr-use', 'lnicm', 'no-op-function', 'structurizecfg', 'scc-oz-module-inliner',
                 'pseudo-probe-update', 'sample-profile', 'no-op-cgscc', 'loop-unroll-full', 'chr', 'invalidate',
                 'poison-checking', 'dot-ddg', 'no-op-loop', 'openmp-opt']

COSTLY_PASSES = ['attributor', 'attributor-cgscc']

VALID_PASSES = ['stack-safety', 'cfl-anders-aa', 'divergence', 'targetlibinfo', 'globals-aa', 'scalar-evolution',
                'cfl-steens-aa', 'regions', 'memoryssa', 'module-summary', 'scoped-noalias-aa', 'demanded-bits',
                'branch-prob', 'stack-safety-local', 'domtree', 'lazy-value-info', 'iv-users', 'postdomtree',
                'basic-aa', 'loops', 'aa', 'da', 'block-freq', 'objc-arc-aa', 'tbaa', 'verify', 'phi-values', 'scev-aa',
                'memdep', 'domfrontier', 'globalopt', 'scalarizer', 'load-store-vectorizer',
                'rewrite-statepoints-for-gc', 'separate-const-offset-from-gep', 'unify-loop-exits', 'objc-arc',
                'name-anon-globals', 'lower-guard-intrinsic', 'objc-arc-contract', 'lower-matrix-intrinsics',
                'loop-rotate', 'strip-nonlinetable-debuginfo', 'lowertypetests', 'strip-gc-relocates', 'forceattrs',
                'reassociate', 'infer-address-spaces', 'libcalls-shrinkwrap', 'div-rem-pairs', 'simple-loop-unswitch',
                'gvn-sink', 'early-cse-memssa', 'add-discriminators', 'sroa', 'memcpyopt', 'guard-widening',
                'jump-threading', 'strip', 'coro-cleanup', 'break-crit-edges', 'canonicalize-aliases', 'reg2mem',
                'openmp-opt-cgscc', 'instrprof', 'loop-distribute', 'sink', 'adce', 'loop-simplifycfg',
                'loop-extract-single', 'function-attrs', 'post-inline-ee-instrument', 'view-cfg', 'indvars',
                'float2int', 'loop-versioning-licm', 'called-value-propagation', 'fix-irreducible', 'loop-unroll',
                'cg-profile', 'partial-inliner', 'pgo-memop-opt', 'correlated-propagation', 'lcssa',
                'lower-widenable-condition', 'assume-builder', 'always-inline', 'wholeprogramdevirt', 'tailcallelim',
                'function-specialization', 'sccp', 'dot-cfg', 'mergefunc', 'iroutliner', 'loop-reduce',
                'aggressive-instcombine', 'globalsplit', 'instcombine', 'lowerswitch', 'mergereturn', 'loop-reroll',
                'loop-load-elim', 'verify', 'instsimplify', 'strip-dead-prototypes', 'argpromotion', 'vector-combine',
                'ee-instrument', 'objc-arc-apelim', 'loop-extract', 'scalarize-masked-mem-intrin', 'loop-idiom',
                'strip-dead-debug-info', 'nary-reassociate', 'loop-vectorize', 'insert-gcov-profiling', 'constmerge',
                'loop-data-prefetch', 'hotcoldsplit', 'slsr', 'mem2reg', 'instrorderfile', 'pgo-icall-prom',
                'rpo-function-attrs', 'annotation-remarks', 'globaldce', 'simplifycfg', 'loweratomic',
                'speculative-execution', 'strip-nondebug', 'lower-constant-intrinsics', 'coro-early',
                'make-guards-explicit', 'gvn', 'inferattrs', 'bdce', 'loop-deletion', 'licm', 'elim-avail-extern',
                'loop-versioning', 'early-cse', 'loop-predication', 'gvn-hoist', 'cross-dso-cfi', 'inject-tli-mappings',
                'lowerinvoke', 'loop-instsimplify', 'coro-elide', 'rewrite-symbols', 'extract-blocks',
                'annotation2metadata', 'lower-expect', 'loop-interchange', 'strip-debug-declare', 'view-cfg-only',
                'inline', 'dot-cfg-only', 'irce', 'instnamer', 'deadargelim', 'objc-arc-expand', 'loop-unroll-and-jam',
                'dce', 'alignment-from-assumptions', 'loop-simplify', 'ipsccp', 'slp-vectorizer', 'loop-fusion',
                'loop-sink', 'consthoist', 'partially-inline-libcalls', 'mldst-motion', 'aa-eval',
                'redundant-dbg-inst-elim', 'loop-flatten', 'callsite-splitting', 'newgvn', 'dse', 'assume-simplify',
                'lint', 'constraint-elimination', 'coro-split', 'transform-warning', 'canon-freeze',
                'lower-matrix-intrinsics-minimal', 'mergeicmps', 'dfa-jump-threading', 'instcount', 'bounds-checking']

DANGEROUS_PASSES = ['memprof-module', 'memprof', 'pgo-instr-gen', 'internalize', 'metarenamer']
